site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme: readthedocs


markdown_extensions:
  - footnotes # æ”¯æŒè„šæ³¨
  - admonition # æ”¯æŒæç¤ºå—
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

## for mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js






plugins:
  - search
  #- mknotebooks
  - mkdocs-jupyter