site_name: JELLY


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme:     
  name: readthedocs
  highlight: false
  #hljs_languages:
  #  - yaml
  #  - rust
  #  - c
  #  - python
  #  - r 
  #  - julia
  #logo: img/favicon.png

## mathjax for .md
markdown_extensions:
  - footnotes # 支持脚注
  - admonition # 支持提示块
  #- pymdownx.superfences # 支援語法上色
  - pymdownx.arithmatex: # 支持 latex 語法
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - stylesheets/style.css

plugins:
  - search
  - mkdocs-jupyter
  - with-pdf
