site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme: material


markdown_extensions:
  - footnotes # æ”¯æŒè„šæ³¨
  - admonition # æ”¯æŒæç¤ºå—
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

## for mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js






plugins:
  - search
  #- mknotebooks
  - mkdocs-jupyter