site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme: readthedocs


markdown_extensions:
  - pymdownx.arithmatex:  # MathJaxæ”¯æ´
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math

plugins:
  - search
  - mkdocs-jupyter