site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme: readthedocs

## mathjax for .md
markdown_extensions:
  - footnotes # æ”¯æŒè„šæ³¨
  - admonition # æ”¯æŒæç¤ºå—
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  #- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


## mathjax for .ipynb
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#markdown_extensions:
#  - mdx_math

plugins:
  - search
  - mkdocs-jupyter