site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme:     
  name: readthedocs
  highlightjs: false  # é—œé–‰é è¨­çš„ç¨‹å¼ç¢¼æ¡†


## mathjax for .md
markdown_extensions:
  - footnotes # æ”¯æŒè„šæ³¨
  - admonition # æ”¯æŒæç¤ºå—
  - pymdownx.superfences # æ”¯æ´èªæ³•ä¸Šè‰²
  - pymdownx.arithmatex: # æ”¯æŒ latex èªæ³•
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML


plugins:
  - search
  - mkdocs-jupyter