site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme: readthedocs


## mathjax for .md
markdown_extensions:
  - footnotes # æ”¯æŒè„šæ³¨
  - admonition # æ”¯æŒæç¤ºå—
  - pymdownx.arithmatex: # æ”¯æŒèªæ³•ä¸Šè‰²
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML


plugins:
  - search
  - mkdocs-jupyter