site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme: readthedocs


markdown_extensions:
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true



plugins:
  - search
  - mkdocs-jupyter