site_name: ğŸ¿ POPCORN


#nav:
#  - ipynb:
#    - ch3: ch3.ipynb

theme: readthedocs


markdown_extensions:
  - footnotes # æ”¯æŒè„šæ³¨
  - admonition # æ”¯æŒæç¤ºå—
  - pymdownx.details
  - pymdownx.superfences

## for mathjax
extra_javascript:
  - javascripts/mathjax.js



plugins:
  - search
  - mkdocs-jupyter